### ISSUE TITLE
Pin payments not finalizing on Production

### ISSUE THREAD

**Issue by sstead** [openfoodfoundation/openfoodnetwork#1256]
![image](https://cloud.githubusercontent.com/assets/10843056/20824274/6608bffe-b8af-11e6-9043-1236de98dbb1.png)

They payment method is all setup correctly I believe... Secret, live API key was used. Server: 'live'

![image](https://cloud.githubusercontent.com/assets/10843056/20824292/97455dac-b8af-11e6-9c09-e045580239cf.png)

**Comment by RohanM** [comment]
I saw this error in the logs as:

```yaml
Gateway Error
  --- !ruby/object:ActiveMerchant::Billing::Response
params:
  error: invalid_resource
  error_description: One or more parameters were missing or invalid
  messages:
  - param: card.number
    code: card_number_invalid
    message: Card number can't be blank
  - param: card.cvc
    code: card_cvc_invalid
    message: Card cvc can't be blank
  - param: amount
    code: amount_invalid
    message: Amount must be at least 100 ($1.00 AUD)
message: One or more parameters were missing or invalid
success: false
test: false
authorization: 
fraud_review: 
error_code: 
emv_authorization: 
avs_result:
  code: 
  message: 
  street_match: 
  postal_match: 
cvv_result:
  code: 
  message: 
```

I could replicate the problem by mirroring prod data and attempting a payment in development

ActiveMerchant doesn't seem to have any significant changes to pin gateway between our version (v1.50.0) and the latest (v1.61.0), so it's less likely that an upgrade to ActiveMerchant will solve the problem.
