### ISSUE TITLE
[Spree 2.1] models/payments_spec and lib/open_food_network/user_balance_calculator_spec (3 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4890]
```
25) Spree::Payment applying transaction fees to Stripe payments when the payment fails makes the transaction fee ineligible and finalizes it
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `any?' for nil:NilClass
      #   ./app/models/spree/stock/availability_validator_decorator.rb:27:in `line_item_shipment'

  26) Spree::Payment applying transaction fees to Stripe payments when the payment information is invalid makes the transaction fee ineligible and finalizes it
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `any?' for nil:NilClass
      #   ./app/models/spree/stock/availability_validator_decorator.rb:27:in `line_item_shipment'

```
