### ISSUE TITLE
[Spree 2.1] Fix credit card cc_type

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4895]
Credit cards missing `cc_type` attribute...

```
 10) InjectionHelper only injects credit cards with a payment profile
      Failure/Error: object.cc_type.capitalize
      
      NoMethodError:
        undefined method `capitalize' for nil:NilClass
      # ./app/serializers/api/credit_card_serializer.rb:6:in `brand'
      # (eval):4:in `_fast_attributes'
      # ./app/helpers/injection_helper.rb:135:in `inject_json_ams'
      # ./app/helpers/injection_helper.rb:117:in `inject_saved_credit_cards'
      # ./spec/helpers/injection_helper_spec.rb:73:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NameError:
      #   NameError
      #   ./app/helpers/injection_helper.rb:135:in `inject_json_ams'

11) Spree::CreditCardsController#update when the specified credit card is found and the card is owned by the user when the update completes successfully renders a serialized copy of the updated card
      Failure/Error: object.cc_type.capitalize
      
      NoMethodError:
        undefined method `capitalize' for nil:NilClass
      # ./app/serializers/api/credit_card_serializer.rb:6:in `brand'
      # (eval):4:in `_fast_attributes'
      # ./app/controllers/spree/credit_cards_controller.rb:26:in `update'
      # ./spec/controllers/spree/credit_cards_controller_spec.rb:100:in `block (7 levels) in <top (required)>'
      # ./spec/controllers/spree/credit_cards_controller_spec.rb:100:in `block (6 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `capitalize' for nil:NilClass
      #   ./app/serializers/api/credit_card_serializer.rb:6:in `brand'

34) Credit Cards as a logged in user passes the smoke test
      Failure/Error: object.cc_type.capitalize
      
      ActionView::Template::Error:
        undefined method `capitalize' for nil:NilClass
      # ./app/serializers/api/credit_card_serializer.rb:6:in `brand'
      # (eval):4:in `_fast_attributes'
      # ./app/helpers/injection_helper.rb:135:in `inject_json_ams'
      # ./app/helpers/injection_helper.rb:117:in `inject_saved_credit_cards'
      # ./app/views/spree/users/show.html.haml:4:in `block in _daaebdba37c5226cbfb47d7fc0e0d8ae'
      # ./app/views/spree/users/show.html.haml:1:in `_daaebdba37c5226cbfb47d7fc0e0d8ae'
      # ./lib/open_food_network/rack_request_blocker.rb:36:in `call'
      # ------------------
      # --- Caused by: ---
      # NameError:
      #   NameError
      #   ./app/helpers/injection_helper.rb:135:in `inject_json_ams'

  53) Api::CreditCardSerializer serializes a credit card
      Failure/Error: object.cc_type.capitalize
      
      NoMethodError:
        undefined method `capitalize' for nil:NilClass
      # ./app/serializers/api/credit_card_serializer.rb:6:in `brand'
      # (eval):4:in `_fast_attributes'
      # ./spec/serializers/api/credit_card_serializer_spec.rb:8:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # NoMethodError:
      #   undefined method `capitalize' for nil:NilClass
      #   ./app/serializers/api/credit_card_serializer.rb:6:in `brand'

  54) Api::CreditCardSerializer formats an identifying string with the card number masked
      Failure/Error: object.cc_type.capitalize
      
      NoMethodError:
        undefined method `capitalize' for nil:NilClass
      # ./app/serializers/api/credit_card_serializer.rb:6:in `brand'
      # ./app/serializers/api/credit_card_serializer.rb:20:in `formatted'
      # ./spec/serializers/api/credit_card_serializer_spec.rb:12:in `block (2 levels) in <top (required)>'
```
