### ISSUE TITLE
[Spree 2.1] Fix services/cart_service_spec (2 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4897]
```
 44) CartService end-to-end populate adds a variant
      Failure/Error: line_items << current_item
      
      TypeError:
        can't cast RSpec::Mocks::Double to string
      # ./app/models/spree/order_decorator.rb:165:in `add_variant'
      # ./app/services/cart_service.rb:47:in `cart_add'
      # ./app/services/cart_service.rb:41:in `attempt_cart_add'
      # ./app/services/cart_service.rb:28:in `block in attempt_cart_add_variants'
      # ./app/services/cart_service.rb:26:in `each'
      # ./app/services/cart_service.rb:26:in `attempt_cart_add_variants'
      # ./app/services/cart_service.rb:19:in `block in populate'
      # ./app/services/cart_service.rb:17:in `populate'
      # ./spec/services/cart_service_spec.rb:24:in `block (4 levels) in <top (required)>'

  45) CartService end-to-end populate updates a variant's quantity, max quantity and final_weight_volume
      Failure/Error: current_item.save
      
      TypeError:
        can't cast RSpec::Mocks::Double to string
      # ./app/models/spree/order_decorator.rb:155:in `add_variant'
      # ./app/services/cart_service.rb:47:in `cart_add'
      # ./app/services/cart_service.rb:41:in `attempt_cart_add'
      # ./app/services/cart_service.rb:28:in `block in attempt_cart_add_variants'
      # ./app/services/cart_service.rb:26:in `each'
      # ./app/services/cart_service.rb:26:in `attempt_cart_add_variants'
      # ./app/services/cart_service.rb:19:in `block in populate'
      # ./app/services/cart_service.rb:17:in `populate'
      # ./spec/services/cart_service_spec.rb:35:in `block (4 levels) in <top (required)>'a
```
