### ISSUE TITLE
[Spree 2.1] Fix services/restart_checkout_spec and requests/checkout/stripe_connect_spec (8 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#4898]
```
 46) RestartCheckout#call when the order is in a subsequent state when order ship address is nil resets the order state, and clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (596, null, 184, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'

  47) RestartCheckout#call when the order is in a subsequent state when order ship address is not empty resets the order state, and clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (600, null, 187, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'

  48) RestartCheckout#call when the order is in a subsequent state when order ship address is empty does not reset the order state nor clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (604, null, 190, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'

```

These 3 specs are also failing on the clean up stage after the spec succeeds so I am adding them to the scope of this issue:
rspec ./spec/requests/checkout/stripe_connect_spec.rb:134
rspec ./spec/requests/checkout/stripe_connect_spec.rb:207
rspec ./spec/requests/checkout/stripe_connect_spec.rb:223

**Comment by Matt-Yorkley** [comment]
Possibly related: https://github.com/rails/rails/issues/34358

**Comment by Matt-Yorkley** [comment]
It looks like this record with `null` attribute that's causing the error has to be a `Spree::Calculator`. The error only occurs after the test has completely finished and the data is being removed by `DatabaseCleaner.clean`...

**Comment by luisramos0** [comment]
similar thing to #4890

**Comment by Matt-Yorkley** [comment]
Okay, there's something nasty going on here. This is what I've got so far:

- Some transactions related to saving associated objects are partially failing and being left open
- It looks like an error is being raised somewhere and maybe rescued in an unexpected way (or stopping a secondary error from propagating) during the saving of those objects (that's the "stack level too deep" bit)
- DatabaseCleaner then attempts to forcefully close all open transactions after the example has run (to clean up), which is triggering SQL updates with invalid data _after the test has finished_. 
- In this example the object in the broken transaction is a `Spree::Calculator`, and there are 3 created here as part of either a `ShippingMethod` or `PaymentMethod`.

Bumping the `database_cleaner` version changes the errors slightly and displays this warning during the examples: `WARNING: there is already a transaction in progress`. The error is now:

```
WARNING: there is already a transaction in progress

SystemStackError: stack level too deep

  0) RestartCheckout#call when the order is in a subsequent state when order ship address is nil resets the order state, and clears incomplete shipments and payments
     Failure/Error: DatabaseCleaner.clean

     SystemStackError:
       stack level too deep
     # ./spec/spec_helper.rb:112:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "created_at" violates not-null constraint
     #   DETAIL:  Failing row contains (12302, null, 0.00, 0.00, null, 0.00, null, null, null, null, null, null, 0.00, null, null, null, null, null, null, null, null, null, null).
     #   ./spec/spec_helper.rb:112:in `block (2 levels) in <top (required)>'
```
This record is not a `Spree::Calulator` :point_up:...

**Comment by Matt-Yorkley** [comment]
If we follow the suggestion here: https://github.com/rails/rails/issues/17776#issuecomment-65140214 ...and enable `config.eager_load = true` in `environments/test.rb` we get some very interesting new error output:

```
SystemStackError: stack level too deep

  0) RestartCheckout#call when the order is in a subsequent state when order ship address is nil resets the order state, and clears incomplete shipments and payments
     Failure/Error: ensure_correct_adjustment_without_included_tax

     SystemStackError:
       stack level too deep
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_d<...>t_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./app/models/spree/shipment_decorator.rb:4:in `ensure_correct_adjustment_with_included_tax'
     # ./spec/factories/shipment_factory.rb:34:in `block (3 levels) in <top (required)>'
     # ./spec/services/restart_checkout_spec.rb:16:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:111:in `block (2 levels) in <top (required)>'
```

I think this method in `shipment_decorator.rb` is what we're looking for @luisramos0  :point_up:
