### ISSUE TITLE
[Spree 2.1] Checkout: null value in column "calculable_type"

### ISSUE THREAD

**Issue by Matt-Yorkley** [openfoodfoundation/openfoodnetwork#4902]
```
  46) RestartCheckout#call when the order is in a subsequent state when order ship address is nil resets the order state, and clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (596, null, 184, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'

  47) RestartCheckout#call when the order is in a subsequent state when order ship address is not empty resets the order state, and clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (600, null, 187, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'

  48) RestartCheckout#call when the order is in a subsequent state when order ship address is empty does not reset the order state nor clears incomplete shipments and payments
      Failure/Error: config.after(:each)            { DatabaseCleaner.clean }
      
      SystemStackError:
        stack level too deep
      # ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "calculable_type" violates not-null constraint
      #   DETAIL:  Failing row contains (604, null, 190, null, null, null).
      #   ./spec/spec_helper.rb:113:in `block (2 levels) in <top (required)>'
```
