### ISSUE TITLE
docker image published to dockerhub ?

### ISSUE THREAD

**Issue by albjeremias** [openfoodfoundation/openfoodnetwork#5074]
## What is the problem we are solving 
It takes a long time to build all this docker image.. maybe it's a choice.. but would be great if for each tag an image is pushed into docker hub!

## Success factors = expected outcome 
If this is sucessful, then we will have a more simple way to deploy this project into any place :) it's also more ecological, we will use less cpu power.

**Comment by NickMoignard** [comment]
Good idea, many open source platforms are using this way.
We can import docker images from docker hub directly in the docker-compose file.
That means, we don't build in docker-compose, just import images from public docker hub repo.

**Comment by NickMoignard** [comment]
````
 web:
     tty: true
     stdin_open: true
     image: openfoodnetwork/ofnweb:v2
   ports:
     - 3000:3000
   volumes:
    ...
````
Like above we can import docker image from docker hub
