### ISSUE TITLE
[Rails 4.1] spec/models/spree/variant_spec.rb (2 broken specs)

### ISSUE THREAD

**Issue by luisramos0** [openfoodfoundation/openfoodnetwork#6193]
Fix two specs in the rails-4-1 branch.

This can be seen here in the rails-4-1-latest:
```
  2) Spree::Variant#in_stock? when stock_items are not backorderable when stock_items out of stock return false if stock_items out of stock
     Failure/Error: expect(variant.in_stock?).to be_falsy
     
       expected: falsey value
            got: true
     # ./spec/models/spree/variant_spec.rb:241:in `block (5 levels) in <module:Spree>'

 3) Spree::Variant indexing variants by id indexes variants by id
     Failure/Error: scoped.index_by(&:id)
     
     NameError:
       undefined local variable or method `scoped' for #<Class:0x0000563a51169c20>
     # ./app/models/spree/variant.rb:139:in `indexed'
     # ./spec/models/spree/variant_spec.rb:442:in `block (3 levels) in <module:Spree>'

```
